apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: nsms
  name: apptwo
  labels:
    app: apptwo
spec:
  template:
    metadata:
      labels:
        app: apptwo
        tier: web
    spec:
      containers:
        - name: apptwo
          image: inserito/apptwo:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: nsms
  name: apptwo
  labels:
    app: apptwo
spec:
  type: NodePort
  selector:
    app: apptwo
    tier: web
  ports:
    - port: 8080
      targetPort: 8080